spring:
  datasource:
    url: jdbc:mysql://10.164.194.142:3306/crm?characterEncoding=utf-8&useSSL=false
    testWhileIdle: true
    validationQuery: SELECT 1 from dual
    username: crm
    password: Admin@123
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      show-sql: false
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      connectio:
        characterEncoding: utf8
        useUnicode: true
        charSet: UTF-8
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
other:
  datasource:
    url: jdbc:mysql://10.164.194.142:3306/portal?characterEncoding=utf-8&useSSL=false
    testWhileIdle: true
    validationQuery: SELECT 1
    username: portal
    password: Admin@123
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      show-sql: false
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
